"""Añade campo created a Post

Revision ID: 262155567f30
Revises: cb86527f8105
Create Date: 2020-01-15 11:53:21.518238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262155567f30'
down_revision = 'cb86527f8105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'created')
    # ### end Alembic commands ###
